HOCS-2457 add Spring config to allow Swagger service on casework
UKHomeOffice/hocs-casework pull request #380
Opened 2021-04-01 13:00 UTC by abarker66

This ticket adds a Swagger service to casework giving us access to all the exposed api endpoints published by the casework service.
The Swagger page is available at http://localhost:8082/swagger-ui.html

2021-04-06 10:47 UTC, robertdeniszczyc2 approved these changes
Looks good to me

2021-04-06 11:10 UTC, robertdeniszczyc2 requested changes
As with info service as this uses identical implementation, has the acceptance criteria around being available on dev only being covered?

Thanks,
Rob

2021-04-13 14:27 UTC, abarker66 commented
Spring profile switching is now added. The profile is 'swagger' and can be added as an env variable or as a -D JVM command line option. So without the 'swagger' profile there will be no swagger endpoints available.

2021-04-13 15:40 UTC, robertdeniszczyc2 approved these changes

2021-04-13 15:52 UTC, merged