HOCS-3189 Upgrading to gradle 7.1 and spring boot 2.5.1 works locally
UKHomeOffice/hocs-casework pull request #391
Opened 2021-06-18 14:10 UTC by gardnersam

2021-07-01 15:06 UTC, robertdeniszczyc2 requested changes

2021-07-01 15:06 UTC, robertdeniszczyc2 commented on src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataTimelineCaseIntegrationTest.java
> +import com.fasterxml.jackson.datatype.jsr310.JSR310Module;
This is unused so can be removed

2021-07-02 12:56 UTC, gardnersam commented on src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataTimelineCaseIntegrationTest.java
> +import com.fasterxml.jackson.datatype.jsr310.JSR310Module;
Removed

2021-07-02 13:03 UTC, robertdeniszczyc2 approved these changes
Looks good to me

2021-07-02 13:51 UTC, merged