HOCS-3299: Add endpoint for active stage by Case UUID
UKHomeOffice/hocs-casework pull request #394
Opened 2021-06-29 13:21 UTC by ARobinson26

- Added a new endpoint the allows you to get the active stage for a case by it's UUID.
- Added a new method in StageService that ensures only one stage is returned.

2021-06-29 13:41 UTC, SeanReedHomeOffice requested changes

2021-06-29 13:41 UTC, SeanReedHomeOffice commented on src/main/java/uk/gov/digital/ho/hocs/casework/api/StageService.java
> +    Stage getActiveStageByCaseUUID(UUID caseUUID){
It would be better to return an Optional<Stage> from this function.

2021-06-29 13:41 UTC, SeanReedHomeOffice commented on src/main/java/uk/gov/digital/ho/hocs/casework/api/StageService.java
> +        log.debug("Getting Active Stages for Case: {}", caseUUID);
Debug message needs fixing. Stage without the 's'.

2021-09-07 09:18 UTC, nickmcmahon01 commented
Closing PR because it's over 2 months old.

2021-09-07 09:18 UTC, closed without merging