HOCS-4269 - UNCAUGHT_EXCEPTION: Exception: null, Stack: java.lang.Nul…
UKHomeOffice/hocs-casework pull request #502
Opened 2021-12-03 16:19 UTC by agraham19

…lPointerException

For some reason all of the lines after the first are getting cut off the stacktraces
for uncaught exceptions. This problem does not occur in info-service, so this PR
replaces some of the logging lines with a copy and paste from the correctly function
service.

2021-12-07 11:50 UTC, fewtrees-ho requested changes
Does this change fix the problem though?

2021-12-08 09:46 UTC, agraham19 commented
> Does this change fix the problem though?

It attempts to address the logging bug so we can debug the null pointer error.

2021-12-08 09:53 UTC, LiamMacP approved these changes
For the issue in question, the correlation ID isn't showing any surrounding logs so we are stabbing in the dark. This should atleast give us the underlying exception. We can then look into potentially why we haven't got surrounding logs...

2021-12-08 10:05 UTC, fewtrees-ho approved these changes

2021-12-08 10:06 UTC, merged